// ABIs for the zkSync and Ethereum bridge smart contracts

const ZkSyncBridgeABI = [
    // Insert the ABI array for the zkSync bridge smart contract here.
    // This data is usually provided in the JSON file generated by the Solidity compiler.
];

const EthereumBridgeABI = [
    // Insert the ABI array for the Ethereum bridge smart contract here.
    // This data is similar to the zkSync bridge contract ABI and is obtained in the same way.
];

module.exports = {
    ZkSyncBridgeABI,
    EthereumBridgeABI
};
